[project]
name = "axiom-research"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "en-core-web-sm",
    "google-genai>=2.25.0",
    "ipykernel>=7.4.0",
    "numpy>=2.5.3",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "spacy>=3.8.16",
]

[dependency-groups]
dev = [
    "nbconvert>=7.17.1",
]

[tool.uv.sources]
en-core-web-sm = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl" }
